
services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./app.py"
    depends_on:
      - db
    ports:
      - '5000:5000'

  db:
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306'